### ISSUE TITLE
Error while running mnist benchmark

### ISSUE THREAD

**Issue by yeshwanthv5** [kclip/FL-SNN#2]
Hello @nskat 
I am trying to run `benchmark_mnist.sh` with default parameters. I am running into the following error. The spiking history variable doesn't seem to be considering timesteps in the first layer. Or this might because of a PyTorch version mismatch. I am using `1.4.0`. Please let me know if I am missing something

Thanks
```
Traceback (most recent call last):
  File "mnist_test.py", line 95, in <module>
    train(network, input_train, output_train, indices, learning_rate, kappa, deltas, alpha, r)
  File "/Users/yesh/Learning/snn/FL-SNN/utils/training_utils.py", line 171, in train
    log_proba, learning_signal, eligibility_trace = feedforward_sampling(network, training_sequence[indices[0]], eligibility_trace, learning_signal, s, S_prime, alpha, r)
  File "/Users/yesh/Learning/snn/FL-SNN/utils/training_utils.py", line 106, in feedforward_sampling
    log_proba = network(example[:, s % S_prime])
  File "/Users/yesh/Learning/snn/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/yesh/Learning/snn/FL-SNN/SNN.py", line 129, in forward
    self.spiking_history = self.update_spiking_history(input_signal)
  File "/Users/yesh/Learning/snn/FL-SNN/SNN.py", line 236, in update_spiking_history
    spiking_history[self.visible_neurons, -1] = input_signal
RuntimeError: shape mismatch: value tensor of shape [686, 80] cannot be broadcast to indexing result of shape [686]
```

**Comment by nskat** [comment]
Hi, so sorry for not responding for a long time, the repo was not actively maintained and other projects got in the way. 
It's now been reworked somewhat profoundly and should work, I'm closing the issue but don't hesitate to reopen if needed.
